title: Scalable algorithms in applicable mathematics
author: Ed Bueler
email: elbueler@alaska.edu
github_username: bueler
markdown: kramdown
theme: jekyll-theme-cayman
#kramdown:
#  math_engine: mathjax
