title: Scalable algorithms in applicable mathematics
author: Ed Bueler
email: elbueler@alaska.edu
github_username: bueler
#description:
theme: cayman
markdown: kramdown
kramdown:
  math_engine: mathjax
